[package]
name.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "chimera_ffi"
crate-type = ["cdylib"]

[features]
default = ["mimalloc"]
ffi-trace = ["uniffi/ffi-trace"]
jemallocator = ["dep:tikv-jemallocator"]
mimalloc = ["dep:mimalloc"]

[dependencies]
uniffi.workspace = true
jni = "0.22"
tokio = "1"
async-compat.workspace = true
once_cell = "1"
ipnet = "2"
eyre = "0.6"
bytes = "1"
# Logging
tracing = "0.1"
tracing-error = "0.2"
time = { version = "0.3", features = ["macros", "local-offset"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["std", "fmt"]}
paranoid-android = "0.2"
color-eyre = "0.6"

[dependencies.clash-lib]
package = "clash-lib"
branch = "master"
git = "https://github.com/MFSGA/Chimera_Client.git"
# TODO: Align features with upstream when ready
features = [
    "ws",
    "trojan",
    "hysteria",
    "tproxy",
    "redir",
    "http_port",
    "mixed_port",
    "tracing",
]
default-features = true

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.9"

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
